apiVersion: v1
kind: ReplicationController
metadata:
  name: miniapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: miniapp
    spec:
      containers:
      - name: miniapp
        image: criss1790/ms-usuarios-admins:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: production
          - name: MONGO_URL
            value: mongodb+srv://Ecommerce-usuarios-admin:xGnUFYVISjB4Pp9V@cluster0.l1qxo.mongodb.net/Ecommerce-usuarios-admin?retryWrites=false&w=majority&ssl=true

